export const MEDICINES_MOCK = [
    { id: '1', name: 'Paracetamol', type: 'Tablet', defaultDosage: '500mg', defaultFreq: '1-0-1' },
    { id: '2', name: 'Amoxicillin', type: 'Capsule', defaultDosage: '500mg', defaultFreq: '1-0-1' },
    { id: '3', name: 'Cetirizine', type: 'Tablet', defaultDosage: '10mg', defaultFreq: '0-0-1' },
    { id: '4', name: 'Pantoprazole', type: 'Tablet', defaultDosage: '40mg', defaultFreq: '1-0-0' },
    { id: '5', name: 'Azithromycin', type: 'Tablet', defaultDosage: '500mg', defaultFreq: '1-0-0' },
    { id: '6', name: 'Metformin', type: 'Tablet', defaultDosage: '500mg', defaultFreq: '1-0-1' },
    { id: '7', name: 'Ibuprofen', type: 'Tablet', defaultDosage: '400mg', defaultFreq: '1-0-1' },
    { id: '8', name: 'Omeprazole', type: 'Capsule', defaultDosage: '20mg', defaultFreq: '1-0-0' },
    { id: '9', name: 'Ranitidine', type: 'Tablet', defaultDosage: '150mg', defaultFreq: '1-0-1' },
    { id: '10', name: 'Atorvastatin', type: 'Tablet', defaultDosage: '10mg', defaultFreq: '0-0-1' },
    { id: '11', name: 'Amlodipine', type: 'Tablet', defaultDosage: '5mg', defaultFreq: '1-0-0' },
    { id: '12', name: 'Metoprolol', type: 'Tablet', defaultDosage: '50mg', defaultFreq: '1-0-1' },
    { id: '13', name: 'Losartan', type: 'Tablet', defaultDosage: '50mg', defaultFreq: '1-0-0' },
    { id: '14', name: 'Telmisartan', type: 'Tablet', defaultDosage: '40mg', defaultFreq: '1-0-0' },
    { id: '15', name: 'Gabapentin', type: 'Capsule', defaultDosage: '300mg', defaultFreq: '0-0-1' },
    { id: '16', name: 'Levothyroxine', type: 'Tablet', defaultDosage: '50mcg', defaultFreq: '1-0-0' },
    { id: '17', name: 'Montelukast', type: 'Tablet', defaultDosage: '10mg', defaultFreq: '0-0-1' },
    { id: '18', name: 'Clopidogrel', type: 'Tablet', defaultDosage: '75mg', defaultFreq: '1-0-0' },
    { id: '19', name: 'Aspirin', type: 'Tablet', defaultDosage: '75mg', defaultFreq: '1-0-0' },
    { id: '20', name: 'Vitamin D3', type: 'Sachet', defaultDosage: '60k IU', defaultFreq: 'Once a week' },
];
